[package]
name = "netti"
version = "0.1.0"
authors = ["Kasperi Kuuskoski <kasperi.kuuskoski@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.9.0"
gio = "0.9.1"
glib = "0.10.0"
nom = "6.0.1"